start_year = 1979
end_year = 1980

nveg = 14
enable_routing = true
enable_snow = true
fillvalue_threshold = 1e15

[output]
dir         = "../output_data/global/"
file_prefix = "outputfile_global_"
format      = "netcdf"

[input]
[input.paths]
input_param_file       = "../input_data/global/vic_global_5min_params_fix2_f32.nc"
coverage_file          = "../input_data/global/vic_global_5min_domain.nc"
routing_param_file     = "../input_data/global/routing/vic_global_5min_routing_param_wbt_f32.nc"

precipitation_file     = "../input_data/global/forcing/prec/prec_WFDE5_CRU+GPCC_v2.0_5arcmin_f32_"
air_temperature_file   = "../input_data/global/forcing/tair/tair_WFDE5_v2.0_5arcmin_f32_"
wind_speed_file        = "../input_data/global/forcing/wind/wind_WFDE5_v2.0_5arcmin_f32_"
vapor_pressure_file    = "../input_data/global/forcing/vp/vp_WFDE5_v2.0_5arcmin_f32_"
shortwave_down_file    = "../input_data/global/forcing/swdown/swdown_WFDE5_v2.0_5arcmin_f32_"
longwave_down_file     = "../input_data/global/forcing/lwdown/lwdown_WFDE5_v2.0_5arcmin_f32_"
surface_pressure_file  = "../input_data/global/forcing/psurf/psurf_WFDE5_v2.0_5arcmin_f32_"

[input.names]
