name: CI tests

on:
  push:
    branches:
      - CI

permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Run validation script
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repo
      - uses: actions/checkout@v4

      # 2. Set up Julia
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      - name: Install Julia dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate()'

      # 3. Set up Python & Numpy
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install numpy netCDF4

      # 4. Execute the script
      - name: Run validations
        run: bash run_validations.sh

